# Generated by Django 4.1.7 on 2024-11-10 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0002_alter_baykearticle_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('spu_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykeshopsku', verbose_name='商品')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykeuserinfo', verbose_name='用户')),
            ],
        ),
    ]
