# Generated by Django 4.1.7 on 2024-11-11 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0004_alter_browsehistory_spu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsehistory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykeuserinfo', verbose_name='用户'),
        ),
    ]
