# Generated by Django 4.1.7 on 2024-11-11 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0005_alter_browsehistory_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsehistory',
            name='spu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykeshopspu', verbose_name='商品'),
        ),
    ]
